import { Case, Communication, WorkloadMetric } from './types'

// Sample case data
export const sampleCases: Case[] = [
  {
    id: 'CASE-001',
    clientName: 'Amira Collins',
    clientId: 'CLI-4521',
    caseType: 'Contribution issue',
    status: 'In progress',
    slaHours: 24,
    hoursRemaining: 3,
    lastActivity: 'Client contacted support',
    lastActivityTime: '30 min ago',
    riskLevel: 'critical',
    recommendedAction: 'Call client',
    notes: 'Client waiting for contribution confirmation',
    priority: 1,
    reopened: false,
    highValue: true,
    complianceFlag: false,
    noActivityDays: 0,
  },
  {
    id: 'CASE-002',
    clientName: 'Daniel Wright',
    clientId: 'CLI-3847',
    caseType: 'Grant request',
    status: 'Waiting on client',
    slaHours: 48,
    hoursRemaining: 18,
    lastActivity: 'Awaiting client documents',
    lastActivityTime: '2 hours ago',
    riskLevel: 'high',
    recommendedAction: 'Send follow-up email',
    notes: 'Documents overdue by 1 day',
    priority: 2,
    reopened: true,
    highValue: false,
    complianceFlag: false,
    noActivityDays: 2,
  },
  {
    id: 'CASE-003',
    clientName: 'Priya Shah',
    clientId: 'CLI-5203',
    caseType: 'Account update',
    status: 'New',
    slaHours: 24,
    hoursRemaining: 22,
    lastActivity: 'Case created',
    lastActivityTime: '2 hours ago',
    riskLevel: 'low',
    recommendedAction: 'Review and assign',
    notes: 'Standard account update request',
    priority: 3,
    reopened: false,
    highValue: false,
    complianceFlag: true,
    noActivityDays: 0,
  },
  {
    id: 'CASE-004',
    clientName: 'Marcus Lee',
    clientId: 'CLI-2156',
    caseType: 'Document review',
    status: 'In progress',
    slaHours: 72,
    hoursRemaining: 45,
    lastActivity: 'Sent for internal review',
    lastActivityTime: '4 hours ago',
    riskLevel: 'medium',
    recommendedAction: 'Follow up with advisor',
    notes: 'Awaiting legal review sign-off',
    priority: 4,
    reopened: false,
    highValue: true,
    complianceFlag: true,
    noActivityDays: 1,
  },
  {
    id: 'CASE-005',
    clientName: 'Sofia Ramirez',
    clientId: 'CLI-6789',
    caseType: 'Advisor follow-up',
    status: 'Waiting on internal team',
    slaHours: 48,
    hoursRemaining: 32,
    lastActivity: 'Advisor assignment pending',
    lastActivityTime: '6 hours ago',
    riskLevel: 'medium',
    recommendedAction: 'Escalate',
    notes: 'Advisor team at capacity',
    priority: 5,
    reopened: false,
    highValue: false,
    complianceFlag: false,
    noActivityDays: 0,
  },
  {
    id: 'CASE-006',
    clientName: 'James Patterson',
    clientId: 'CLI-4412',
    caseType: 'Compliance review',
    status: 'Escalated',
    slaHours: 48,
    hoursRemaining: 12,
    lastActivity: 'Escalated to compliance',
    lastActivityTime: '12 hours ago',
    riskLevel: 'critical',
    recommendedAction: 'Call client',
    notes: 'Regulatory deadline approaching',
    priority: 6,
    reopened: false,
    highValue: true,
    complianceFlag: true,
    noActivityDays: 0,
  },
  {
    id: 'CASE-007',
    clientName: 'Elena Rodriguez',
    clientId: 'CLI-7823',
    caseType: 'Donor question',
    status: 'Waiting on client',
    slaHours: 24,
    hoursRemaining: 8,
    lastActivity: 'Clarification needed from donor',
    lastActivityTime: '16 hours ago',
    riskLevel: 'high',
    recommendedAction: 'Call client',
    notes: 'Multiple attempts to reach out unsuccessful',
    priority: 7,
    reopened: false,
    highValue: false,
    complianceFlag: false,
    noActivityDays: 3,
  },
  {
    id: 'CASE-008',
    clientName: 'Michael Chen',
    clientId: 'CLI-9245',
    caseType: 'Contribution issue',
    status: 'Ready to close',
    slaHours: 24,
    hoursRemaining: 100,
    lastActivity: 'Resolution sent to client',
    lastActivityTime: '1 hour ago',
    riskLevel: 'none',
    recommendedAction: 'Close case',
    notes: 'Client confirmed satisfied',
    priority: 8,
    reopened: false,
    highValue: false,
    complianceFlag: false,
    noActivityDays: 0,
  },
]

export const sampleCommunications: Communication[] = [
  {
    id: 'COM-001',
    type: 'email',
    from: 'Amira Collins',
    subject: 'RE: Contribution confirmation needed',
    timestamp: '30 min ago',
    unread: true,
    relatedCaseId: 'CASE-001',
  },
  {
    id: 'COM-002',
    type: 'email',
    from: 'Daniel Wright',
    subject: 'Grant application status',
    timestamp: '2 hours ago',
    unread: true,
    relatedCaseId: 'CASE-002',
  },
  {
    id: 'COM-003',
    type: 'note',
    from: 'Internal team',
    subject: 'Legal review requires clarification',
    timestamp: '4 hours ago',
    unread: false,
    relatedCaseId: 'CASE-004',
  },
  {
    id: 'COM-004',
    type: 'email',
    from: 'Sofia Ramirez',
    subject: 'Follow-up needed on account',
    timestamp: '1 day ago',
    unread: false,
    relatedCaseId: 'CASE-005',
  },
]

export const morningBriefData = [
  { label: 'Cases Assigned Today', value: '3', trend: 'up' as const, change: 2 },
  { label: 'Urgent Cases', value: '4', trend: 'up' as const, change: 1 },
  { label: 'Overdue Follow-ups', value: '2', trend: 'stable' as const },
  { label: 'Avg Response Time', value: '2.4h', trend: 'down' as const, change: -0.6 },
]

export const workloadData: WorkloadMetric[] = [
  { status: 'New', count: 1 },
  { status: 'In progress', count: 2 },
  { status: 'Waiting on client', count: 2 },
  { status: 'Waiting on internal team', count: 1 },
  { status: 'Escalated', count: 1 },
  { status: 'Ready to close', count: 1 },
]

export const riskCases = sampleCases.filter(
  (c) =>
    c.riskLevel === 'critical' ||
    c.riskLevel === 'high' ||
    c.hoursRemaining < 12 ||
    c.reopened ||
    c.noActivityDays >= 3
)
